project:
  type: website

website:
  title: "advancedhigherstatistics.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: textbook.qmd
        text: Course Textbook
      - href: resources.qmd
        text: Teaching Resources
      - href: exams.qmd
        text: Past Exams
      - href: links.qmd
        text: Useful Links

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true

editor: source

